################################################################################
#
# libsolv
#
################################################################################

LIBSOLV_VERSION = 0.7.14
LIBSOLV_SITE = $(call github,openSUSE,libsolv,$(LIBSOLV_VERSION))
LIBSOLV_LICENSE = BSD-3-Clause
LIBSOLV_LICENSE_FILES = LICENSE.BSD

HOST_LIBSOLV_DEPENDENCIES = host-bzip2 host-libxml2 host-lzma host-zchunk host-zstd host-rpm

HOST_LIBSOLV_CONF_OPTS = \
	-DENABLE_STATIC=OFF \
	-DDISABLE_SHARED=OFF \
	-DENABLE_PERL=OFF \
	-DENABLE_PYTHON=OFF \
	-DENABLE_RUBY=OFF \
	-DENABLE_TCL=OFF \
	-DUSE_VENDORDIRS=OFF \
	-DENABLE_RPMDB=ON \
	-DENABLE_RPMPKG=ON \
	-DENABLE_PUBKEY=OFF \
	-DENABLE_RPMDB_BYRPMHEADER=ON \
	-DENABLE_RPMDB_LIBRPM=ON \
	-DENABLE_RPMDB_BDB=ON \
	-DENABLE_RPMPKG_LIBRPM=ON \
	-DENABLE_RPMMD=ON \
	-DENABLE_SUSEREPO=OFF \
	-DENABLE_COMPS=OFF \
	-DENABLE_HELIXREPO=OFF \
	-DENABLE_DEBIAN=OFF \
	-DENABLE_MDKREPO=OFF \
	-DENABLE_ARCHREPO=OFF \
	-DENABLE_CUDFREPO=OFF \
	-DENABLE_HAIKU=OFF \
	-DENABLE_CONDA=OFF \
	-DENABLE_APPDATA=OFF \
	-DMULTI_SEMANTICS=ON \
	-DENABLE_LZMA_COMPRESSION=ON \
	-DENABLE_BZIP2_COMPRESSION=ON \
	-DENABLE_ZSTD_COMPRESSION=ON \
	-DENABLE_ZCHUNK_COMPRESSION=ON \
	-DWITH_SYSTEM_ZCHUNK=ON \
	-DWITH_LIBXML2=ON \
	-DWITHOUT_COOKIEOPEN=OFF \
	-DENABLE_COMPLEX_DEPS=1

$(eval $(host-cmake-package))
